[![Issue Labeled](https://github.com/jrin0340-420/astroglider/actions/workflows/issue-labeled.yml/badge.svg?branch=feature%2Fprototype-core&event=create)](https://github.com/jrin0340-420/astroglider/actions/workflows/issue-labeled.yml)
